insarlab/MintPy

- docs/CODEOWNERS
add CODEOWNERS to enable `Require review from code owner` option.
> add docs/CODEOWNERS

- pysar/plot_coherence_matrix.py
- pysar/subset.py
- sh/plot_pysarApp.sh
+ plot_coherence_matrix: add support for geocoded ifgramStack.h5
+ subset: bug fixed for -o/--output option
+ detect geometryGeo.h5 file if geometryRadar.h5 does not exists.
> plot_coherence_matrix: support geo coded insar stack

- docs/conda.txt
- requirements.txt
> updated minimum dask_jobqueue version

- pysar/utils/readfile.py
- pysar/utils/writefile.py
utils/readfile:
+ exclude `.full` while checking FILE_TYPE for ISCE binary files
+ more generic read_binary() by do not distinguish num_band
utils/writefile: update comments
> utils/readfile: bug fix while reading ISCE file with full in filename

- pysar/ifgram_inversion.py
Lets put this back when the rsmas_insar requirements.txt has been updated.
> remove temporarily `import dask`

- .gitignore
- pysar/defaults/dask_pysar.yaml
- pysar/defaults/pysarApp.cfg
- pysar/defaults/pysarApp_template.txt
- pysar/ifgram_inversion.py
- pysar/objects/pysarobj.py
- pysar/tropo_pyaps3.py
- pysar/view.py
+ add tropo_pyaps3.py in response to pyaps3 from Angelique Benoit on Github
+ add `parallel` template option
+ move dask and job_queue inside main function and import them only if `inps.parallel == True`
> support pyap3

- pysar/prep_gamma.py
+ merge `extract_metadata4dem_geo()`  and `extract_metadata4lookup_table` into `extract_metadata4geometry_geo()`
+ rename `extract_metadata4dem_radar()` to `extract_metadata4geometry_radar()`
+ searching for LAT/LON_REF1/2/3/4 info for geometry files in radar coordinates
+ move code inside prepare_metadata() into main()
> prep_gamma: add LAT/LON_REF1/2/3/4 info to geometry files

- docs/conda.txt
- docs/installation.md
- pysar/version.py
- requirements.txt
+ auto grab code version and date using git commands
+ do not install pykml through conda channel, which will cause error; install py2/3-pykml from yunjunz through Anaconda's pip
+ remove openmp from requirements.txt as it's not directly used by pysar, it's used by pyresample implictly
> version: auto grab code version and date

- pysar/pysarApp.py
- test/test_pysarApp.py
+ add argument parsing functions to be more user friendly.
+ add --dir to be able to change test directory
+ add --nofresh to be able to start processing not from the scratch, suitable for testing bugs in the middle of processing.
> test/test_pysarApp: add argument parsing

- pysar/geocode.py
- pysar/objects/pysarobj.py
> geocode: fix typo in help

- CONTRIBUTING.md
- mintpy/version.py
+ fix bug for version when there is no new commits after the latest release
+ fix link to Google Group in CONTRIBUTING
> version: bug fix when no new commit after the latest release

- mintpy/prep_gamma.py
check off_file and generate it automatically if without; 
fix bugs for dem_par file.
> prep_gamma: add gamma command to generate *.off file if missing

- mintpy/defaults/dask.yaml
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/defaults/smallbaselineApp_auto.cfg
- mintpy/ifgram_inversion.py
- mintpy/utils/utils.py
I added a function `move_dask_stdout_stderr_files()` to `utils/utils.py`. Is that the correct place? Let me know if you want me to put is somewhere else. @yunjunz 
Also there is a `utils0.py` and `utils1.py` which I don't know what they do. Are they used?
> add dask walltime option

- mintpy/asc_desc2horz_vert.py
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/ifgram_inversion.py
> asc_desc2horz_vert: checking spatial resolution

- docs/conda.txt
- mintpy/ifgram_inversion.py
- mintpy/view.py
> remove gdal>=3.0 from docs/conda.txt

- mintpy/prep_aria.py
bperp is read from the metadata
bperp calculation function and required dirs are removed
> prep_aria: grab bperp from metadata directly

- mintpy/save_kmz_timeseries.py
+ bug fixed for masking with input --mask file.
+ add --steps and --lods options to be able to customize the details setup
+ check file existance and coordinates of input files
+ add get_aux_filename() for default aux files
+ adjust split_into_sub_boxes() and get_boxes4deforming_area() to take step as argument instead of win_size
+ adjust print out message in the terminal
+ clean the following functions:
- create_regionalized_networklinks_file()
- generate_network_link()
- main()
> refactoring save_kmz_timeseries.py

- mintpy/objects/stack.py
- mintpy/objects/stackDict.py
- mintpy/save_kmz_timeseries.py
- mintpy/simulation/variance.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/utils0.py
- mintpy/utils/variance.py
+ remove duplicated get_lat_lon()
+ fix typo in doc for datatype of connectComponent
>  remove duplicated get_lat_lon()

- mintpy/save_kmz_timeseries.py
+ get rid of global variables
+ use `shutil` and `os` modules to create/move files/directories instead of calling shell commands using os.system()
+ support full path, so that the script can be ran in other directories.
+ simplified output message
> refactoring save_kmz_timeseries 2

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/prep_aria.py
> assign no-data pixel to zero for ARIA connComp

- mintpy/asc_desc2horz_vert.py
- mintpy/objects/coord.py
- mintpy/utils/plot.py
objects/coord: check_box_within_data_coverage(): add print_msg to control the message output
utils/plot:read_dem(): support DEM file that does not cover the input geo_box completely by filling the outside area with NaN
> view.py: support background DEM smaller than input data

- mintpy/match.py
> fixed indent bug

- mintpy/load_data.py
Add check_files_size() to check the file size of a list of files.
Adjust read_subset_box() to check the bounding box if 1) no input subset and 2) processor is snap.
> load_data: temp fix the file size inconsistency for SNAP products

- docs/README.md
- docs/examples/input_files/FernandinaSenDT128.txt
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/geocode.py
- mintpy/load_data.py
- mintpy/prep_gamma.py
- mintpy/utils/readfile.py
- mintpy/view.py
+ prep_gamma.extract_metadata4geometry_geo(): calculate Y_FIST from corner/post_east metadata
+ geocode.metadata_radar2geo(): use X/Y_UNIT from lookup file metadata if they exists
+ view.plot_slice(): add code to plot geo-coord in meters based on the code for radar-coord data and adjust for:
- the extent
- axis ticklabel rotation
+ add SNAP processor to doc
+ switch GAM for FernandinaSenDT128.txt from ERAI to ERA5
> support GAMMA lookup file with coordinates in meters

- docker/Dockerfile
- docker/README.md
- docs/installation.md
Added instructions to run the Docker container from Dockerhub to Installation.md
Also added a root level docker directory for the dockerfile. Please review whether this is the right place, or even necessary. In this way anyone can inspect or modify the dockerfile and build their own container instead of using the prebuilt one on dockerhub.
> Initial Docker image with config file

- mintpy/objects/gps.py
- mintpy/utils/plot.py
- mintpy/utils/utils.py
- mintpy/utils/utils1.py
+ utils.plot.plot_gps(): search existing geometry files with incidenceAngle dataset and use it to convert GPS enu to LOS.
+ utils.utils1.get_file_list(): bug fix related with coord argument
+ utils.utils1.get_geometry_file(): add work_dir to support searching while runing script not in the directory of the input file.
> plot_gps: search/use geometry file for incAngle if available

- test/test_smallbaselineApp.py
Should not calling smallbaselineApp.py through its main() in a loop which has different insar processors, becuase it changes the global variable datasetName2templateKey during load_data.read_inps_dict2geometry_dict_object()
With my laptop, testing all 3 datasets now takes less than 9 mins.
> bug fixed in test_smallbaselineApp.py

- docs/installation.md
- mintpy/plot_coherence_matrix.py
- mintpy/prep_aria.py
- mintpy/utils/utils.py
+ ut.transect_yx() remove masked out pixels.
+ bug fix for plot_coherence_matrix.py
+ add docker cmd  and link to installation.md
> remove masked out pixel while plotting transection

- mintpy/prep_aria.py
- mintpy/view.py
prep_aria.py
+ add --water-mask option to load watermask.msk file into geometryGeo.h5
+ add ARIA-tools example commands into usage
view.py: fix bug of saving figure to file while runing command in a different dir than the input file.
> prep_aria: add waterMask

- mintpy/dem_error.py
- mintpy/ifgram_inversion.py
- mintpy/load_data.py
- mintpy/modify_network.py
- mintpy/prep_aria.py
- mintpy/smallbaselineApp.py
- mintpy/tropo_pyaps3.py
- mintpy/version.py
update template comments in individual scripts
Update version.py
> pre-release wrap up

- docs/README.md
- mintpy/objects/stackDict.py
- mintpy/prep_aria.py
- mintpy/smallbaselineApp.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- mintpy/utils/utils1.py
As for now, GPS enu2los conversion for ARIA products would work if the azimuth angle is not loaded and not written in geometryGeo.h5 file, then the code will use incidence angle and head angle calculated from metadata. For a small area, this would be fine.
The azimuthAngle inconsistency from ARIA-tools and topsStack is not exactly 90 degrees difference, thus, I don't have a solution until Emre or David give me a clear explanation #162.
> check azimuthAngle while plotting gps vs insar

- mintpy/ifgram_inversion.py
+ commenting out ts_std dataset to reduce memory usage
+ remove obsolete --split-file option to simplify the code
> ifgram_inversion: comment out ts_std to reduce memory usage

- mintpy/generate_rdc_lt.py
- mintpy/lookup_geo2radar.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/utils0.py
Convert the Geo-coordinates based lookup-table (GAMMA, ROI_PAC) into the Radar-coordinates based lookup-table (ISCE).
> convert lookup-tables under geo-coord to radar-coord

- mintpy/prep_aria.py
- mintpy/utils/plot.py
- mintpy/view.py
> prep_aria: convert azAngle from ARIA to ISCE style

- mintpy/lookup_geo2radar.py
- mintpy/objects/resample.py
@yunjunz please check and finish the left part to update self
> update lookup_geo2radar.py using scipy.interpolate.griddata

- mintpy/ifgram_inversion.py
- mintpy/info.py
- mintpy/objects/stack.py
info.py: add --dset option to printout the dataset value for easy checking the dataset of HDF5 file
objects/stack:
+ rename openH5() to open_hdf5()
+ add open and close functions inside write2hdf5_block() so that file is properly closed always.
ifgram_inversion:
+ adjust for the updated timeseries.write2hdf5_block() so that the file is properly closed even if the program is terminated in the middle of running.
> info: add --dset option to print out dataset

- mintpy/load_gbis.py
- mintpy/save_gmt.py
- mintpy/utils/plot.py
load_gbis: add metadata DEFORMATION_MODEL
utils/plot.auto_shared_lalo_location(): new function to return the lat/lon label location in tuple of 4 int, for multiple subplots.
> load_gbis: add DEFORMATION_MODEL

- .github/config.yml
- mintpy/load_gbis.py
- mintpy/utils/plot.py
.github/config.yml: update message for opening pull request
load_gbis.py: fix bug when input inversion result is based on one track of insar data only.
utils/plot.get_poly_mask(): improved color while selecting roipoly.
**Reminders**
> load_gbis: bug fix for single track inversion result

- docs/tutorials/README.md
- mintpy/view.py
- sh/load_data_aoi.sh
+ add links to jupyter notebook of ARIA-tools-doc
+ sh/load_data_aoi.sh: update comment
+ view: reduce cbar length in ratio for multiple subplots with large figure height
**Reminders**
>  add links to jupyter notebook of ARIA-tools-doc

- docs/tutorials/smallbaselineApp_aria.ipynb
simplify titles in smallbaselineApp_aria
**Reminders**
> simplify titles in smallbaselineApp_aria

- mkdocs.yml
> adjust readthedocs sidebar

- .gitignore
- mintpy/load_hdf5.py
- mintpy/mask.py
+ assign default fill value to np.nan.
+ change matrix data type to float32 if 1) fill value is nan AND 2) input original data type does not support NaN.
**Reminders**
> mask: auto check and convert data type to float32

- docs/google_earth.md
- mintpy/asc_desc2horz_vert.py
- mintpy/process_isce_stack.py
- mintpy/smallbaselineApp.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- sh/plot_smallbaselineApp.sh
> smallbaselineApp: check key 'mintpy.networkInversion.shadowMask'

- mintpy/generate_mask.py
- mintpy/geocode.py
- mintpy/plot_transection.py
- mintpy/utils/plot.py
- mintpy/utils/utils.py
plot_transection:
+ add support for multiple input files in geo coordinates with different spatial resolutions by using geo coordinate to grab transection data
+ upgrade --offset option to support one number or exact number of offset as input files
+ utils/utils.py: add transect_lines() to extract continuous transection data along multiple lines
generate_mask:
+ add --revert option
+ enable main() calling from external script
utils/plot.get_poly_mask(): improved plotting for dataset with non-negative value, such as DEM
geocode: print cmd in cmd_line_parse()
**Reminders**
> transection: support files with different resolution in geo coord

- mintpy/reference_point.py
- mintpy/save_gbis.py
- mintpy/utils/plot_ext.py
- sh/plot_smallbaselineApp.sh
Fix bug when input reference y/x has valid 0 value.
**Reminders**
> reference_point: fix bug when input ref_y/x is 0

- mintpy/save_hdfeos5.py
- mintpy/save_kmz_timeseries.py
add -o / --output to specify output file name
add --wrap to be able to re-wrap the velocity for color coding.
expose --cutoff and --min-percentage options to modify the default high resolution output for deforming areas.
**Reminders**
> save_kmz_ts: new options for customize display

- docs/installation.md
> update pyaps account setup info

- mintpy/load_gbis.py
- mintpy/plot_transection.py
load_gbis: remove obsolete metadata calculation
**Reminders**
> plot_transection: bug fix for --off option

- mintpy/objects/gps.py
- mintpy/objects/insar_vs_gps.py
- mintpy/utils/plot.py
- mintpy/view.py
> add start/end_date to insar_vs_gps()

- mintpy/objects/insar_vs_gps.py
- mintpy/utils/utils1.py
> bugs fix for insar_vs_gps()

- mintpy/objects/gps.py
- mintpy/utils/plot.py
added feature to write out GPS velocities which fall into the study area to a CSV file.
> Write GPS LOS velocities to CSV file

- docs/README.md
- mintpy/smallbaselineApp.py
> copy cfg files to pic folder

- mintpy/objects/gps.py
- mintpy/utils/ptime.py
- sh/plot_smallbaselineApp.sh
> utils function for GSI F3 GPS daily solution

- mintpy/utils/plot.py
change from column name 'Site ID' to 'SiteID' in GPSSitesVel.csv file.
**Reminders**
> plot.plot_gps: remove whitespace in site ID while saving to CSV

- docs/ports.txt
- mintpy/load_data.py
- mintpy/utils/readfile.py
+ Update ports.txt to run ARIA-tools in macports
+ Support loading geometry files only in load_data.py
+ Support reading binary files with 3 or 4 bands.
**Reminders**
> load geometry*.h5 only from load_data.py

- mintpy/objects/stack.py
- mintpy/prep_aria.py
- mintpy/simulation/simulation.py
- mintpy/utils/readfile.py
> fix the slight inconsistency of x/y spacing between different ARIA GUNW products

- mintpy/asc_desc2horz_vert.py
> check/update reference point in asc_desc2horz_vert.py

- mintpy/save_kmz.py
+ add --cbar-loc option to modify the location of colorbar screen overlay
+ fix the not working issue of --cbar-bin-num and --cbar-label
+ remove the obsolete --cbar-height option
**Reminders**
> save_kmz: add --cbar-loc option

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/save_kmz.py
- mintpy/save_kmz_timeseries.py
> replace zip command with zipfile module

- docs/ports.txt
- mintpy/ifgram_inversion.py
- mintpy/prep_isce.py
- mintpy/save_kmz.py
- mintpy/save_kmz_timeseries.py
- mintpy/simulation/simulation.py
> more robust coherence2variance calculation

- docs/resources/colormaps/README.md
- mintpy/diff.py
- mintpy/objects/colors.py
- mintpy/objects/stack.py
- mintpy/prep_isce.py
- mintpy/simulation/fractal.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
+ improved reading for isce int file
+ updated ncorrlooks value for Sentinel-1 TOPS data
+ new colormap: cmy
**Reminders**
> improved read/plot for isce binary files

- mintpy/boot_strap.py
- input is time series file in MintPy format
- output is bootstrap estimation of velocity and uncertainty in MintPy velocity file format
**Reminders**
> boot strapping tool to estimate velocity and uncertainty from MintPy time series file

- mintpy/prep_isce.py
- mintpy/simulation/fractal.py
- mintpy/utils/utils1.py
prep_isce.py:
+ add get_processor()
+ read_baseline_timeseries() ignore files with different reference date
utils/utils1.py: add get_center_lat_lon() to extract the scene center lat/lon from geometry file.
**Reminders**
> fix potential bug while reading isce baseline

- mintpy/asc_desc2horz_vert.py
- mintpy/simulation/fractal.py
+ add recon_power_spectral_density() to recon freq/psd from input p0 and beta.
+ asc_desc2horz_vert.py
- add ref_file argument while writing output as time-series file
- change decimal digits from 4 to 3 while checking the reference point.
**Reminders**
> fractal: add recon_power_spectral_density()

- mintpy/objects/sensor.py
- mintpy/simulation/fractal.py
+ fix bug when the custom project name doesn't have the sensor in Capitalize style for `sensor.project_name2sensor_name()`
+ fractal: more comments on regime argument.
**Reminders**
> bug fix for sensor.project_name2sensor_name()

- mintpy/save_gmt.py
> bug fixed for save_gmt.py

- mintpy/add.py
- mintpy/dem_error.py
- mintpy/diff.py
- mintpy/objects/stack.py
- mintpy/reference_date.py
- mintpy/save_hdfeos5.py
- mintpy/save_kmz.py
- mintpy/smallbaselineApp.py
- mintpy/spatial_average.py
- mintpy/temporal_filter.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- mintpy/utils/utils1.py
- mintpy/view.py
> smallbaselineApp: able to skip plot_network

- docs/README.md
- mintpy/view.py
+ view.py: support data operation on the fly for binary files with undefined band dataset names
+ Update README.md
**Reminders**
> view: support data operation for undefined binary files

- mintpy/view.py
- sh/plot_smallbaselineApp.sh
> plot_smallbaselineApp: add connectComponent

- mintpy/objects/gps.py
- mintpy/utils/plot.py
- mintpy/view.py
objects/gps.py:
+ add min_num_solution argument to search_gps() to discard stations with too few solutions, which can be too little for velocity calculation.
+ update the default GPS solution version from IGS08 to IGS14 because the later contains more data and is consistent with the station list file. The original IGS08 data is still supported.
utils/plot.py: simplify the CSV file writing code
**Reminders**
> change default UNR GPS solution version from IGS08 to IGS14

- mintpy/utils/plot.py
- mintpy/view.py
utils/plot.plot_dem_background():
+ calculate extent in geo coordinates
+ add extent for ax.imshow() for both shaded relief and contour
+ remove obsolete latlon argument from contour()
**Reminders**
> fix bug in plotting DEM background

- mintpy/objects/gps.py
> bug fixed for print message in gps.py

- docs/google_earth.md
- mintpy/save_kmz_timeseries.py
> add defo area example figure

- mintpy/generate_mask.py
> temp coh mask: do not change input min temp coh of 0

- mintpy/remove_ramp.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/utils1.py
- mintpy/view.py
> fix bug for remove_ramp.py ifgramStack.h5

- docs/README.md
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/defaults/template.py
- mintpy/diff.py
- mintpy/ifgram_inversion.py
- mintpy/load_data.py
- mintpy/multilook.py
- mintpy/objects/stack.py
- mintpy/objects/stackDict.py
- mintpy/plot_coherence_matrix.py
- mintpy/plot_network.py
- mintpy/prep_isce.py
- mintpy/select_network.py
- mintpy/smallbaselineApp.py
- mintpy/spatial_average.py
- mintpy/temporal_derivative.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- mintpy/utils/utils.py
- mintpy/utils/utils1.py
- mintpy/utils/writefile.py
- mintpy/view.py
- sh/plot_smallbaselineApp.sh
Add the following changes to support the displacement time-series analysis from a stack of offset field.
+ multilook: add --margin option to prepare geometry files that are consistent with offset files.
+ add the following template options to load offset data and invert offset stack.
- mintpy.load.azOffFile
- mintpy.load.rgOffFile
- mintpy.load.offSnrFile
- mintpy.networkInversion.maskDataset = offsetSNR
+ support offset/phase in ifgram_inversion.py and load_data.py
+ plot_network: first dirty version of network plot for offsetSNR
+ adjustments in utils/readfile.py, utils/writefile.py, prep_isce.py
Other unrelated changes.
**Reminders**
> offset time-series

- mintpy/ifgram_inversion.py
fix bug introduced in the previous commit.
**Reminders**
> bug fix in ifgram_inversion.py

- mintpy/prep_isce.py
- mintpy/utils/plot.py
- mintpy/view.py
utils/plot:
+ support `buffer_year=None` in auto_adjust_xaxis_date()
+ bug fix in read_mask() when comparing length/width between data and mask file
+ add --title4sen in add_figure_argument()
**Reminders**
> bug fix in utils/plot.read_mask()

- docs/README.md
- mintpy/objects/ramp.py
- mintpy/view.py
+ fix bug in view.py regarding referencing on the fly for unwrapPhase* dset
+ move data & figure link to the end of paper info.
**Reminders**
> view: fix bug for referencing on the fly for unwrapPhase* dset

- docs/README.md
- docs/dir_structure.md
- docs/examples/input_files/SanFranSenDT42.txt
- docs/requirements.txt
- mintpy/save_hdfeos5.py
- mintpy/smallbaselineApp.py
update ARIA template option as wildcard for geom files #320 
Update requirements.txt for the max version of dask
**Reminders**
> add more links to example dir structure

- docs/README.md
- mintpy/unwrap_error_phase_closure.py
+ fix the broken link for example datasets in README (thank you @jifarquharson).
+ unw_err_phase_closure: matplotlib backend setting update
**Reminders**
> fix link for example dset in README

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/config.yml
- mintpy/objects/coord.py
- mintpy/objects/stackDict.py
- mintpy/prep_isce.py
- mintpy/save_qgis.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- mintpy/utils/utils0.py
- mintpy/view.py
+ save_qgis: fix bug of missing latitude/longitude dataset in the geometry file #331 found by @lamarashed.
+ save_qgis: add --bbox and --geo-bbox option
+ utils/readfile: add read_gdal_vrt() to support generic binary file reading with vrt file
**Reminders**
> save_qgis: add --bbox option

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/unwrap_error_phase_closure.py
- mintpy/utils/utils1.py
+ use dict.get() to set default value if option/key is missing in the template file, which return an error in smallbaselineApp.py --dostep mode. Related with #339 
+ unwrap_error_phase_closure(): adjust plot_* to allow notebook figure display
+ adjust template comments fort shorter width.
**Reminders**
> utils1: bugfix for translating numWorker = all

- docs/ports.txt
- mintpy/defaults/mintpy.yaml
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/defaults/smallbaselineApp_auto.cfg
- mintpy/ifgram_inversion.py
- mintpy/objects/cluster.py
- mintpy/utils/utils.py
- mintpy/utils/utils1.py
Implemented block-by-block reading and writing with dask in `ifgram_inversion.py` #347. This addition makes `ifgram_inversion` now both computationally and memory efficient. The amount of memory that is used by `ifgram_inversion` can be controlled using the `--memory` command line option or by setting `mintpy.networkInversion.memorySize` in the `smallbaselineApp.cfg` file. 
**Reminders**
> Block by block Writing with Dask

- docs/google_earth.md
- mintpy/objects/conncomp.py
> obj/conncomp: use native skimage to remove small objects

- sh/plot_smallbaselineApp.sh
Reverts insarlab/MintPy#345 for now because it eats up too much memory. 
This simple implementation reduced the runtime in a fair amount, should consider bringing it back once we have a better implementation of view.py.
> Revert "plot_smallbaselineApp.sh: running view.py commands in parallel"

- docs/README.md
- mintpy/ifgram_inversion.py
- mintpy/utils/utils0.py
This PR fixes a bug in utils.utils0.enu2los() for ascending orbit input data found by @liuykai.
ifg_inv.calc_weight(): simple printout msg
Update README.md
**Reminders**
> utils.utils0.enu2los(): bugfix for determining azimuth angle

- mintpy/defaults/mintpy.yaml
> remove /tab in mintpy.yaml

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- test/test_smallbaselineApp.py
Fix CircleCI Config File:
- Add new Test dataset path
- Change Workflow
> circle CI: build_and_test workflow

- .circleci/config.yml
- mintpy/load_data.py
- mintpy/prep_aria.py
- mintpy/prep_fringe.py
- mintpy/prep_giant.py
- mintpy/prep_isce.py
- mintpy/smallbaselineApp.py
- mintpy/tropo_pyaps3.py
to potentially fix the test fail after merging as @dbekaert suggested in #370.
+ merge mintpy/pyaps download and dependencies installation into one run
+ add installation testing for mintpy via smallbaselineApp.py and pyaps via tropo_pyaps3.py
+ remove Kuju dataset from example datasets to save time (the corresponding roipac processor is obsolete)
**Reminders**
> circleci/config.yml: add apt update

- .circleci/config.yml
> circleci/config: add version

- docs/dask.md
- docs/installation.md
- mintpy/multilook.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
+ support cpx output with datasetName='cpx'
+ constrain the band index to the max number of band for isce binary files
plot.scale_data2disp_unit: separate field / power quantities for dB
multilook: move the warning suppress to the script top
fix typo in installation.md
**Reminders**
> readfile.read_binary_file(): support cpx output

- mintpy/defaults/auto_path.py
Reads ISCE_produced watermask
**Reminders**
> defaults/auto_path: added reading of ISCE watermask

- docs/dask.md
- mintpy/objects/ramp.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- mintpy/view.py
+ remove the un-implemented --pts-yx/lalo/file options from tsview.py to avoid confussion.
+ improved implementation of objects.ramp.deramp() for less memory usage.
**Reminders**
> tsview: remove --pts-* options

- mintpy/objects/coord.py
- mintpy/utils/utils1.py
revert the previouly introduced work_dir argument to fix the bug it introduced; and replace it by adding more directory candicates to achive the same functionality.
**Reminders**
> utils1.get_lookup_file(): revert work_dir arg to fix bug

- mintpy/ifgram_inversion.py
- mintpy/prep_aria.py
+ add missing geometry module import for prep_aria.py --update option, as mentioned at #397
+ add missing return box in ifgram_inversion_patch() to fix the issue #398
**Reminders**
> bugfix in prep_aria and ifg_inv

- docs/README.md
- mintpy/save_gdal.py
- mintpy/utils/utils0.py
- mintpy/version.py
+ bugfix in save_gdal.py, as pre-scribed by @4restwilliams in #379 
+ utils/utils0: add lalo/inc_angle_ground2iono_shell_along_los()
+ update the hardwired release version number to 1.2.3
**Reminders**
> wrap-up before releasing version 1.2.3

- mintpy/defaults/auto_path.py
- mintpy/smallbaselineApp.py
Changed the auto default path based on new changes in ISCE which has renamed a few files and folders
**Reminders**
> update default path to the new ISCE diversity naming style

- docs/api/attributes.md
- mintpy/ifgram_inversion.py
- mintpy/load_data.py
- mintpy/objects/sensor.py
- mintpy/prep_aria.py
- mintpy/prep_gamma.py
- mintpy/prep_snap.py
- mintpy/select_network.py
- mintpy/simulation/decorrelation.py
- mintpy/utils/isce_utils.py
- mintpy/utils/network.py
- mintpy/utils/utils0.py
- test/configs/FernandinaSenDT128.txt
+ use NCORRLOOKS for weight calculation as described in #396; when this attribute is not available, use an approximate value from ALOOKS and RLOOKS with the ratio of resolution / pixel_size of Sentinel-1 (1.94).
+ refactor objects.sensor for simpler structure.
+ fix the testing error as described in https://github.com/insarlab/MintPy/commit/5c8326704911be50c01a5eb20084ccfa90ed7cd0#commitcomment-40719147
**Reminders**
> ifg_inv: use NCORRLOOKS for weight calculation

- mintpy/objects/sensor.py
- mintpy/prep_aria.py
- mintpy/utils/isce_utils.py
+ fix inconsistent case style in sensor.SEN['IW1/2/3']['azimuth/range_resolution'] to be snake case and adjust its usage in isce_utils.py, as identified #408.
+ bugfix in prep_aria while accessing A/RLOOKS
**Reminders**
> fix typo in hardwired sentinel-1 resolution

- mintpy/tropo_pyaps.py
- mintpy/utils/ptime.py
+ fix a bug in yyyymmdd2years() identified by @liuykai.
+ remove obsolete date_index()
+ move closest_weather_product_time() to tropo_pyaps.py
**Reminders**
> bugfix in ptime.yyyymmdd2years()

- mintpy/objects/sensor.py
- mintpy/prep_aria.py
- mintpy/prep_fringe.py
- mintpy/prep_snap.py
- mintpy/save_gdal.py
- mintpy/utils/readfile.py
Fix bug described in #415.
**Reminders**
> bugfix in prep_snap

- mintpy/objects/coord.py
- mintpy/utils/plot.py
- mintpy/view.py
+ utils.plot.read_pts2inps():
- bug fix while reshaping the coordinates for multiple points
- add "usecols" for more relaxed text file format
+ update comments in objects.coord.coordinate() and view.py's help message
**Reminders**
> bugfix for utils.plot.read_pts2inps()

- docs/dask.md
- docs/installation.md
- docs/references.md
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/load_data.py
- mintpy/utils/isce_utils.py
This PR enables automatic PLATFORM metadata extraction, without the need of having SAR sensor name in the custom template file path. This simplifies the automatic checking of the sensor name in the "correct_LOD" step, as identified in the [mintpy forum](https://groups.google.com/forum/#!topic/mintpy/ZCiZx13i-wI).
**Reminders**
> extract PLATFORM metadata from ISCE products

- mintpy/utils/writefile.py
fix bug described in #417 
**Reminders**
> fix unicode attribute error in h5 file writing while running diff.py

- mintpy/utils/isce_utils.py
make an exception for missing 'spacecraftname' in metadata
**Reminders**
> isce_utils.py: bug fix for spacecraftname in metadata

- docs/hdfeos5.md
- mintpy/save_hdfeos5.py
- mintpy/smallbaselineApp.py
save_hdfeos5.py and smallbaselineApp.py: add avgSpatialCoh.h5 to S1*.he5 file
**Reminders**
> save_hdfeos5.py and smallbaselineApp.py: add avgSpatialCoh.h5 to S1*.he5 file

- mintpy/view.py
> bugfix for view.py --coastline option

- .gitignore
- mintpy/ifgram_inversion.py
- mintpy/load_data.py
- mintpy/modify_network.py
- mintpy/plot_network.py
- mintpy/select_network.py
- mintpy/smallbaselineApp.py
- mintpy/unwrap_error_phase_closure.py
- mintpy/utils/network.py
- mintpy/utils/readfile.py
- mintpy/utils/utils1.py
- mintpy/view.py
+ rename `ifgramStack_coherence_spatialCoh.txt` to `coherenceSpatialAvg.txt`
+ improved auto skip for `invert_network` and `quick_overview` 
+ `readfile.read_hdf5_file()`: speedup `x/ystep` indexing 
**Reminders**
> improved auto skip for inv_net and quick_overview 

- mintpy/dem_error.py
+ remove the duplicated design matrix func for time func and use the one from stack.timeseries objects instead, because it's more generic and more clear coding #450.
+ use G for the design matrix symbol instead of A, to be consistent with the convension in Yunjun et al. (2019)
**Reminders**
> dem_err: rm duplicated design matrix func for time func

- mintpy/asc_desc2horz_vert.py
asc_desc2horz_vert: add --dset option to be able to customize the dataset to read/use to asc/desc 2 horz/vert conversion, for input file with more than one dataset.
**Reminders**
> asc_desc2horz_vert: add --dset option

- mintpy/prep_aria.py
> prep_aria: bugfix when no template file input

- docs/conda.txt
- docs/installation.md
- mintpy/prep_gamma.py
+ prep_gamma: support *-* folder style, as identified in #458 
+ add pip to conda.txt since it's used in the installation of pykml
**Reminders**
> prep_gamma: support *-* folder style 

- mintpy/prep_aria.py
+ prep_aria: update the metadata against the new bounding box if subset is applied (#459)
**Reminders**
> prep_aria: update metadata after subseting

- docs/hdfeos5.md
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/ifgram_inversion.py
- mintpy/ifgram_reconstruction.py
- mintpy/objects/stack.py
- mintpy/save_hdfeos5.py
- mintpy/tropo_pyaps.py
- mintpy/tropo_pyaps3.py
- mintpy/tsview.py
- mintpy/utils/isce_utils.py
- mintpy/utils/utils0.py
- mintpy/view.py
+ ifgram_inversion: update az/rg_pixel_size to the resolution before multilooking for meaningful value
+ tsview: make REF_Y/X optional to support off time-series
**Reminders**
> ifg_inv for offset: consider A/RLOOKS for az/rg_pixel_size

- docs/demo_dataset.md
- docs/dir_structure.md
- docs/examples/input_files/README.md
- docs/examples/input_files/WCapeSenAT29.txt
- mintpy/load_data.py
- mintpy/objects/stackDict.py
- mintpy/view.py
- test/configs/WCapeSenAT29.txt
- test/test_smallbaselineApp.py
+ bugfix for loading SNAP DEM with subset enabled
+ add an example input dataset processed with SNAP provided by @andretheronsa
+ add an example template file: WCapSenAT29.txt
**Reminders**
> example dataset & template file for SNAP 

- mintpy/mask.py
https://github.com/insarlab/MintPy/issues/475
**Reminders**
> Updated mask.py to work with coherence files and others

- mintpy/match.py
> Added --no-offset option to match.py

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/load_data.py
- mintpy/objects/stack.py
- mintpy/objects/stackDict.py
- mintpy/view.py
- test/test_smallbaselineApp.py
Support to load interferogram amplitude/magnitude via a new optional template option `mintpy.load.magFile`.
**Reminders**
> load magnitude via mintpy.load.magFile

- docs/README.md
- mintpy/load_data.py
- mintpy/utils/readfile.py
- mkdocs.yml
+ utils.readfile.read_attribute(): move *.aux.xml file to the end of the priority list to fix the DEM background bug in view.py while using DEM from aria-tools identified by @parosen.
**Reminders**
> bugfix for view.py with background DEM from aria-tools

- mintpy/tsview.py
Details are here https://github.com/insarlab/MintPy/issues/493
tsview.py was failing when only three InSAR images in the stack
> tsview.py to handle case of three data points in the stack

- docs/installation.md
- mintpy/defaults/template.py
- mintpy/legacy/select_network.py
- mintpy/load_data.py
- mintpy/objects/__init__.py
- mintpy/objects/colors.py
- mintpy/objects/progress.py
- mintpy/save_kmz_timeseries.py
- mintpy/smallbaselineApp.py
- mintpy/utils/plot.py
- mintpy/utils/ptime.py
- mintpy/utils/readfile.py
- mintpy/utils/utils1.py
- setup.py
- test/test_smallbaselineApp.py
+ use `os.path.dirname(mintpy.__file__)` to locate data files to replace the previous relative location using `__file__` of each python script itself. Thank you @pbrotoisworo for the suggestion!
+ setup: comment out openmp, gfortran #497.
+ load_data: make a local copy of global variable datasetName2templateKey so that it can be modified according to different insar processors, in order to be able to call `mintpy.smallbaselineApp.main()` inside test_sbApp.py (#149).
+ move `progressBar` class from utils.ptime.py into objects.progress.py for simplicity
+ move `select_network.py` to legacy folder
**Reminders**
> mintpy.__file__ for data file and setup

- docs/api/colormaps.md
- docs/dask.md
- docs/demo_dataset.md
- mintpy/objects/colors.py
- mintpy/objects/coord.py
- mintpy/objects/stack.py
- mintpy/objects/stackDict.py
- mintpy/smallbaselineApp.py
- mintpy/temporal_average.py
- mintpy/tsview.py
- mintpy/unwrap_error_bridging.py
- mintpy/unwrap_error_phase_closure.py
- mintpy/utils/readfile.py
- mintpy/utils/utils1.py
- mintpy/utils/writefile.py
+ use absolute path for all file names/paths in smallbaselineApp.py
+ use "with h5py.File() as f" syntax to replace "f = h5py.File(); f.close()" for all occurrence in mintpy
+ remove some unused functions:
- timeseries.open_hdf5()
- timeseries.layout_hdf5()
- singleDataset.close()
- unwrap_error_phase_closure.write_hdf5_file_patch()
+ objects.colors: add GMT_CPT_DIR for customizable GMT cpt file locations
- add MINTPY/GMT_CPT_DIR in objects/colors.py for simplicity and flexibility
- fix broken display of scientific colormaps in readthedocs
+ tsview: bugfix
**Reminders**
> sbApp abspath and with h5py.File() syntax

- .circleci/config.yml
- docs/conda_env.yml
- docs/installation.md
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/defaults/smallbaselineApp_auto.cfg
- mintpy/defaults/template.py
- mintpy/local_oscilator_drift.py
- mintpy/smallbaselineApp.py
- mintpy/solid_earth_tides.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- mintpy/view.py
- setup.py
- test/configs/FernandinaSenDT128.txt
- test/configs/SanFranSenDT42.txt
+ add notes to install [`insarlab/PySolid`](https://github.com/insarlab/PySolid) by default.
+ add `solid_earth_tides.py` to call `pysolid` module for solid Earth tides calculation and correction of time-series file.
+ integrate solid Earth tides correction to the routine workflow `smallbaselineApp.py` via a new step `correct_SET` with `mintpy.solidEarthTides` option
+ testing SET in circle CI
+ update notes for PyAPS installation #497.
**Reminders**
> support solid Earth tides (SET) correction via PySolid

- mintpy/ifgram_inversion.py
- mintpy/objects/sensor.py
- mintpy/save_gbis.py
- mintpy/save_kmz.py
- mintpy/timeseries2velocity.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- test/test_smallbaselineApp.py
+ objects.sensor.standardize_sensor_name(): add str/byte conversion for input sensor name var, as described in google group: https://groups.google.com/g/mintpy/c/rYxGUE_zhX0.
+ save_kmz: add --zero-mask option same as view.py
+ tsview: support --ref-yx if input file don't have REF_Y/X
**Reminders**
> sensor.standardize_sensor_name(): str/bytes conversion

- docs/dask.md
- docs/dir_structure.md
- docs/hdfeos5.md
- mintpy/__init__.py
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/load_data.py
- mintpy/save_hdfeos5.py
- mintpy/smallbaselineApp.py
- mintpy/tropo_pyaps.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/plot.py
- mintpy/view.py
+ load_data: Support add missing metadata from template files, if they are specified manually with key option name in MACRO_CASE/UPPER_CASE.
+ save_hdfeos5: read metadata from template files where key does not starts with mintpy or isce, to easily add missing metadata
**Reminders**
> grab missing attributes from template file for load_data/save_hdfeos5

- mintpy/load_data.py
- mintpy/utils/isce_utils.py
- mintpy/view.py
+ load_data: bugfix for update mode checking when x/ystep > 1
+ isce_utils.read_baseline_timeseries(): ignore empty bperp text files for tops/stripmapStack
+ + view: copy argv to inps for robustness as `sys.argv` behaves differently between in command line and in jupyter notebook.
**Reminders**
> load_data: bugfix for update mode checking when x/ystep > 1

- docs/FAQs.md
- mintpy/info.py
- mintpy/prep_aria.py
- mintpy/tropo_gacos.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/utils0.py
- mintpy/view.py
+ docs/FAQs: add guide for custom input preparation
+ prep_aria: use bnd.ReadAsArray() for consistent style
**Reminders**
> docs/FAQs: add guide for custom input preparation

- docs/api/attributes.md
- docs/hdfeos5.md
- docs/installation.md
- docs/requirements.txt
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/load_data.py
- mintpy/local_oscilator_drift.py
- mintpy/save_kmz_timeseries.py
- mintpy/sh/plot_smallbaselineApp.sh
- mintpy/utils/utils0.py
- mintpy/view.py
+ `view`: show colorbar for multiple subplots with different units by default, for more informative display, e.g. geometryRadar.h5 file
+ `sh/plot_smallbaselineApp.sh`: one liner to find & grab all time-series files and plot them. Shorter code and more compatibility, e.g. GACOS and SET surfix.
+ docs/install: add notes on pysolid for manual compilation
**Reminders**
> view: cbar for subplots with diff units

- .gitignore
- docs/README.md
- mintpy/version.py
+ update version number and release date for v1.3
+ remove solid_f from .gitignore
**Reminders**
> wrap up for version 1.3.0

- .circleci/config.yml
- docs/api/module_hierarchy.md
- mintpy/objects/coord.py
- mintpy/sh/plot_smallbaselineApp.sh
- mintpy/utils/plot.py
- mintpy/utils/ptime.py
- mintpy/utils/readfile.py
Various improvements on the reading, plotting and testings
**Reminders**
> improved read/plot/test

- mintpy/smallbaselineApp.py
- mintpy/utils/utils.py
- mintpy/view.py
- mintpy/workflow/__init__.py
`plot_smallbaselineApp.sh` was translated to a pure Python script. It will save all figures in the output `pic` directory, as described in #531.
Some things to note:
- Method will check if data exists before generating any plot. In my experience not all the figures get generated which leads to an error if it still tries to generate a plot with missing data.
- Only tested with Sentinel-1 data processed using SNAP. I did not test with Envisat or UNAVCO data.
- Tested on a Windows 8 machine
**Reminders**
> platform neutral method for sbApp.plot_result()

- mintpy/dem_error.py
- mintpy/ifgram_inversion.py
- mintpy/remove_ramp.py
- mintpy/smallbaselineApp.py
- mintpy/timeseries2velocity.py
- mintpy/tropo_pyaps.py
- mintpy/tropo_pyaps3.py
- mintpy/unwrap_error_bridging.py
- mintpy/unwrap_error_phase_closure.py
Various spelling corrections.
**Reminders**
> fix minor print typos

- docs/README.md
- docs/dir_structure.md
Links in `docs/README.md` and `docs/dir_structure.md` point at https://hyp3.asf.alaska.edu which is the front page of our beta hyp3 system. for information on the latest and greatest HyP3 which you guys implemented these links should point to https://hyp3-docs.asf.alaska.edu.
**Reminders**
~- [ ] Fix #xxxx~
~- [ ] Pass Codacy code review (green)~
~- [ ] Pass Circle CI test (green)~
~- [ ] Make sure that your code follows our style. Use the other functions/files as a basis.~
~- [ ] If modifying functionality, describe changes to function behavior and arguments in a comment below the function declaration.~
~- [ ] If adding new functionality, add a detailed description to the documentation and/or an example.~
> Fix links for ASF HyP3

- mintpy/asc_desc2horz_vert.py
- mintpy/save_kite.py
save_kite.py
- save velocity, step, or timeseries displ into KITE format (yaml, npz) 
- needs kite and pyrocko module to work.: https://pyrocko.org/ 
- prepared data can be used for inversions in GROND or BEAT
- did not try it with unwrapped ifgs, maybe needs a few edits
small fix in asc_desc ..
- converted azimuth angle from degree to radians in the design matrix
**Reminders**
> add save_kite.py for pyrocko suite

- docs/dir_structure.md
- mintpy/asc_desc2horz_vert.py
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/defaults/smallbaselineApp_auto.cfg
- mintpy/objects/sensor.py
- mintpy/save_kite.py
- mintpy/unwrap_error_phase_closure.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- mintpy/view.py
- test/configs/FernandinaSenDT128.txt
+ view: share x/y axis for multiple subplots
+ add `mintpy.unwrapError.numSample` option
**Reminders**
> view: share x/y axis for multiple subplots

- docs/api/attributes.md
- docs/api/module_hierarchy.md
- mintpy/objects/gps.py
- mintpy/utils/arg_group.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- mintpy/view.py
+ gps: re-use LOS vel/dis from CSV file in view.py
+ view.py: bring back the --update option, whose functionality is lost during the refactoring of the viewer object.
**Reminders**
> gps: re-use LOS vel/dis from CSV file in view.py

- docs/README.md
- docs/dir_structure.md
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/load_data.py
- mintpy/prep_hyp3.py
Related to issue #540
- removes hard coding of EARTH_RADIUS and HEIGHT
- enables use of HyP3 DEM and incidence angle products
- reorganizes main() and add_hyp3_metadata() functions
- updates help information
**Reminders**
> prep_hyp3: update to be compatible with current hyp3 products

- docs/dir_structure.md
- mintpy/smallbaselineApp.py
+ smallbaselineApp.plot_result(): bugfix for the dataset checking of ifgramStack file (#538) identified by @falkamelung.
+ dir_struct*: break line for hyp3 description
**Reminders**
> sbApp.plot_result: bugfix for ifgramStack file

- mintpy/solid_earth_tides.py
> SET: use HEADING if azimuthAngle is not available

- mintpy/objects/stackDict.py
- mintpy/prep_hyp3.py
- mintpy/solid_earth_tides.py
- mintpy/tropo_pyaps3.py
- Changes are made to solid_earth_tides.py to properly compute the pixel spacing from the HyP3 products (see issue https://github.com/insarlab/MintPy/issues/575) and to convert incidence angle from radians to degrees if HyP3 is detected as the processor.
- Changes are made to tropo_pyaps3.py to convert incidence angle from radians to degrees if HyP3 is detected as the processor.
I've got the template for editing the solid_earth_tides.py from @cirrusasf (PR https://github.com/insarlab/MintPy/commit/4ee12c648469937369c968b07e2583f7df8d297e). Pls. check if the changes I've made are correct or if I need to edit these changes. 
**Reminders**
> Proposed changes to solid_earth_tides.py and tropo_pyaps3.py w.r.t. HyP3 products

- mintpy/timeseries2velocity.py
https://github.com/nisar-solid/ATBD/issues/4
**Reminders**
> ts2vel: add --ts-std-file to propagate STD from TS to VEL

- docs/README.md
- docs/conda_env.yml
- docs/installation.md
+ docs/installation: add notes of gdal and isce2 for users with different insar processors
+ docs/conda_env.yml: add gdal since this install a new env from scratch, thus, won't force un-wanted constraint to existing env.
**Reminders**
> install: add notes for gdal and isce2

- docs/demo_dataset.md
- mintpy/ifgram_inversion.py
- mintpy/prep_aria.py
- mintpy/prep_fringe.py
- mintpy/timeseries2velocity.py
- mintpy/tsview.py
- mintpy/utils/arg_group.py
- mintpy/utils/ptime.py
- mintpy/utils/writefile.py
- mintpy/view.py
Hello! I would like to propose to strengthen the current `tsview.py` code to have more abilities on time-series investigation (https://github.com/nisar-solid/ATBD/issues/4).
By appending `--show-model` or `--model`, we can plot the ts2vel model fit (default: False) on the interactive figure.
By specifying `--poly`, `--periodic`, `--step`, `--exp`, `--log`, the code will call `timeseries2velocity.py` here to make a much complex temporal model. The default of the model, if not specified, is a linear function (degree-1 polynomial).
Check the `--help` for details
Using the above model parameters, reconstruct a predicted time series, plot it in the interactive figure (if `--show-model`).
By setting `--savetxt = custom_filename.txt`, we can save the model …
> tsview: reconstruct and plot temporal model

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/defaults/smallbaselineApp_auto.cfg
- mintpy/modify_network.py
- mintpy/objects/stack.py
- mintpy/utils/utils1.py
References Issue #579 
This pull request implements [Kang et al's Effective Coherence Ratio](https://doi.org/10.1016/j.rse.2021.112400) for interferogram selection.
Changes:
modify_network.py:
1.  add section to get_date12_to_drop to perform effective coherence ratio selection
2. modify command line and template parsing so that the above functionality can be accessed
utils1.py:
1. within spatial_average function, allow inversion of mask to allow
for calculation of spatial averages within masked regions
2. when threshold is specified, values above threshold are set to 1
and values below are set to 0. Thus when the spatial average is
calculated, it will represent the proportional area greater than threshold
3. updates stack function calls
4. updates …
> Effective Coherence Ratio Interferogram Selection

- mintpy/objects/stack.py
- mintpy/timeseries2velocity.py
- mintpy/tsview.py
- mintpy/utils/arg_group.py
- mintpy/utils/plot.py
- mintpy/utils/ptime.py
- mintpy/utils/readfile.py
- mintpy/view.py
+ memory-efficient version via auto multilooking
+ support plotting of the confidence interval of the model prediction, following the note from Hanssen et al. (2017) EdX online course [preliminary implementation and NOT thoroughly check!]
**Reminders**
> memory efficient tsview.py for big-data

- docs/conda.txt
- mintpy/prep_fringe.py
- mintpy/subset.py
- mintpy/utils/arg_group.py
- mintpy/utils/ptime.py
+ prep_fringe:
- add --sub-x/y option to load AOI from fringe to mintpy
- add --ps-mask option to load PS mask from fringe to mintpy
- fix sign issue, as confirmed by Yujie.
+ subset: change the default prefix of the output file name from 'subset_' to 'sub_'
+ utils.ptime: add utc2solar_time() to convert UTC time to the local solar time.
+ docs/conda.txt: comment out pyhdf because it's only used for MERRA, which is currently not supported, thus not needed.
**Reminders**
> prep_fringe: fix sign issue & add --sub-x/y --ps-mask options

- mintpy/reference_point.py
- mintpy/save_kmz.py
- mintpy/save_kmz_timeseries.py
- mintpy/utils/arg_group.py
- mintpy/utils/plot.py
- mintpy/view.py
This PR adds the PS-like capability of saving KMZ point/placemark elements for files in radar coordinates, for precise location of high-resolution InSAR points, without the need of geocoding/resampling, thus, is more precise.
**Reminders**
> KML: save velocity in radar-coord as placemarks

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/view.py
+ view: add --show-kept / --show-kept-ifgram option to be able to not plot the dropped interferograms
+ view: more robust dataset index info showing in the title
**Reminders**
> view: add --show-kept(-ifgram) option

- mintpy/image_stitch.py
Very minor bug fixes for the `image_stitch.py` script
**Reminders**
> Small bug fixes for image_stitch.py

- mintpy/objects/cluster.py
Handle the case when none of the env vars are set. Related to #620.
**Reminders**
> num_threads: better handle non-exist env vars

- docs/dask.md
> docs/dask: typo fix

- mintpy/timeseries2velocity.py
Fixing a minor bug  - write_hdf5_block function comes from the writefile import
> ts2vel: skip writing for empty blocks

- mintpy/timeseries2velocity.py
> timeseries2velocity: replace sklearn with numpy for bootstrap resampling

- docs/installation.md
> docs: fix typo in installation.md

- docs/installation.md
- mintpy/objects/resample.py
- mkdocs.yml
- setup.py
These changes add instructions for installing MintPy using Conda on Windows. It also fixes a few bugs that allow windows to run through the examples in the Readme.md file of this repo.
There are still likely bugs as I haven't done any extensive testing on windows.
**Reminders**
> Add doc on install MintPy on Windows

- .circleci/config.yml
- mintpy/objects/coord.py
- mintpy/view.py
+ view: print warning msg for geo-only options if input file is in radar-coord
+ view: print warning msg for single-sub plot options if it has multi-subplots
+ circleci/config.yml: update path for the test_smallbaselineApp.py, which should fix the 
**Reminders**
> view: add WARNING msg for un-support option scenarios

- mintpy/defaults/smallbaselineApp.cfg
- mintpy/ifgram_inversion.py
- mintpy/load_data.py
- mintpy/objects/stack.py
- mintpy/objects/stackDict.py
- mintpy/reference_point.py
- mintpy/timeseries2velocity.py
- mintpy/unwrap_error_phase_closure.py
- mintpy/utils/readfile.py
- mintpy/utils/utils.py
This PR adds the following new features:
1. loading offset STD from ampcor covariance file
2. advanced time-series estimation for offset stacks including:
+ pixel-wise masking based on offset STD
+ able to apply spatial referencing [NO or OFF for flexibility]
+ weighted inversion based on offset STD
3. generic time-series STD propagation from a stack of phase / offset
It also includes some details, e.g. no data value handling, neutral terminology for phase and offset, flexible loading of range offset without azimuth offset, improved default file names for I/O, etc.
**Reminders**
> offset: WLS inversion + masking + TS STD (for phase too)

- mintpy/ifgram_inversion.py
+ Change obsDatasetName for iono timeseries
+ allow for ionoPhase inversion
+ convert iono timeseries unit to meter
**Reminders**
> ifgram_inversion: bugfix for the ionoPhase inversion

- mintpy/asc_desc2horz_vert.py
- mintpy/legacy/2to3_timeseries.py
- mintpy/objects/gps.py
- mintpy/objects/insar_vs_gps.py
- mintpy/tsview.py
- mintpy/utils/plot.py
- mintpy/view.py
This PR adds a function to read GMT lon/lat file so that one can plot the faults dataset (created by GMT from KML file) on top of the view.py plot, in Python level ONLY.
+ add `utils.plot.read_gmt_lonlat_file()` to read and plot faults on top of `view.plot_slice()` output
- add notes and examples on how to prepare the GMT lonlat file from KML file, and use the function in python
+ `objects/gps`:
- add horz angle to the filename if it's horz and print out file name before the long calc
- print warning instead of raise error if no GPS found
- more print out num while comparing with GPS
+ `tsview`: support TS file w/o REF_Y/X
+ `legacy/2to3_timeseries`: change `P_BASELINE_TIMESERIES` to optional
**Reminders**
> API to read GMT lonlat file from KML to plot faults

- .circleci/config.yml
- docs/dir_structure.md
- mintpy/add_attribute.py
- mintpy/load_gbis.py
- mintpy/smallbaselineApp.py
- mintpy/tropo_pyaps.py
- mintpy/tsview.py
- mintpy/utils/readfile.py
- tests/configs/FernandinaSenDT128.txt
- tests/configs/KujuAlosAT422F650.txt
- tests/configs/SanFranSenDT42.txt
- tests/configs/WCapeSenAT29.txt
Various bug fixes as described in the commit-msg.
**Reminders**
> bugfix for hyp3 reading, circle CI and pip/conda install

- docs/installation.md
Add dask configuration to the installation note, as suggested in #725.
**Reminders**
> installation: add dask config to post-install setup

- docs/installation.md
- mintpy/load_data.py
- mintpy/plot_network.py
+ load_data.py: fix a runtime bug when re-run after removing the ISCE stack processing folders
+ plot_network: fix the output file names bug introduced at https://github.com/insarlab/MintPy/pull/693
+ docs/install: a little bit more notes on dask
**Reminders**
> bugfix in load_data.py & plot_network.py

- docs/environment.yml
- docs/requirements.txt
- mintpy/objects/stack.py
- mintpy/timeseries2velocity.py
- mintpy/utils/readfile.py
fix #741 (based on #470)
not thoroughly tested.
**Reminders**
> fix bool array index bug for `h5py>=3`

- docs/api/module_hierarchy.md
- mintpy/generate_mask.py
- mintpy/mask.py
- mintpy/prep_snap.py
- mintpy/reference_point.py
- mintpy/tropo_pyaps3.py
- mintpy/utils/arg_group.py
- mintpy/utils/plot.py
- mintpy/utils/ptime.py
- mintpy/utils/readfile.py
- mintpy/utils/utils0.py
- mintpy/utils/writefile.py
- mintpy/view.py
+ re-write `prep_snap.py` using XML parsing module, to replace the previous text file searching style. This address the reported user forum issue (https://groups.google.com/g/mintpy/c/jdbZ3-EBVMU)..
+ bugfix for the 2-band *.unw file IO in `mask.py`, `reference_point.py` and `tropo_pyaps3.py`
+ `generate_mask.py`: add `--vx / vy / vroipoly` option to be able to specify the AOI for threshold, for more flexible mask generation.
+ `view.py`: add `--no-data-value` option to manually specify the value to ignore/mask during plotting, following #734.
**Reminders**
> refactor prep_snap.py / add readfile.read_snap_dim()

- .circleci/config.yml
- docs/api/module_hierarchy.md
- docs/environment.yml
- docs/installation.md
- docs/requirements.txt
- mintpy/asc_desc2horz_vert.py
- mintpy/image_stitch.py
- mintpy/objects/gps.py
- mintpy/plot_transection.py
- mintpy/save_kmz.py
- mintpy/simulation/variance.py
- mintpy/utils/constants.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- mintpy/utils/utils.py
- mintpy/utils/utils0.py
- setup.py
- tests/configs/RidgecrestSenDT71.txt
- tests/test_asc_desc2horz_vert.py
- tests/test_smallbaselineApp.py
+ `asc_desc2horz_vert.py`: support input geometry files for precise pixel-wised decomposition, useful for large area analysis. @olliestephenson @yuankailiu @rzinke
- refactor the script for the simpler and cleaner sub-functions
- add a unit test for it in `tests/test_asc_desc2horz_vert.py`
+ `image_stitch.py`: support multi-dataset files, e.g. geometry files, to support the new feature in `asc_desc2horz_vert.py`
+ `gps.get_gps_los_obs()`: use `meta` / `obs_type` for a more clear and straightforward usage & add some example usage in the comment for reference. @EJFielding, please update your usage in ATBD notebook accordingly.
+ `plot_transection.py`: support files in radar coordinates 
- bugfix for pip install (https://github.com/yunjunz/MintPy/issues/5) …
> asc_desc2horz_vert: pixel-wise geometry & unit test

- docs/README.md
- mintpy/asc_desc2horz_vert.py
- mintpy/local_oscilator_drift.py
- mintpy/objects/gps.py
- mintpy/utils/plot.py
- mintpy/utils/readfile.py
- mintpy/utils/utils0.py
- tests/test_asc_desc2horz_vert.py
+ utils.readfile.read_snap_dim(): bugfix on WAVELENGTH unit, as reported in the user forum (https://groups.google.com/g/mintpy/c/66m4CcZ__FI)
+ asc_desc2horz_vert: pass angles in deg instead of rad, as suggested by @mgovorcin.
+ utils.plot.auto_adjust_xaxis_date(): fix a bug introduced in https://github.com/insarlab/MintPy/pull/734
+ local_oscilator_drift.get_relative_range_distance(): typo fix
+ docs/README: update aux links in Yunjun et al. (2019)
**Reminders**
> readfile.read_snap_dim(): bugfix on WAVELENGTH unit

- mintpy/objects/sensor.py
- mintpy/smallbaselineApp.py
- mintpy/timeseries2velocity.py
- mintpy/tsview.py
+ tsview.py: bugfix for `cartopy` feature while initializing projection (introduced in #764)
+ timeseries2velocity.read_inps2model(): add print_msg
+ objects/sensor.SEN: fix antenna and PRF parameters
+ smallbaselineApp.py:_read_template(): align the print out "copy for backup" msg
**Reminders**
> tsview: bugfix for cartopy feature

- mintpy/utils/utils1.py
+ utils.utils1.update_template_file():
- add "[]()" to the special symbol interpretation list while searching for template option values, to fix the issue found in https://github.com/nisar-solid/ATBD/pull/26
- use "value2search" for "re.findall()" expression, without changing original value variable, for more robust replace() operation.
**Reminders**
> ut.update_template_file(): support "[]()" during option value search

- mintpy/objects/gps.py
Fix a bug that `site_list_file` will not be downloaded when the user specifies the path to it. https://github.com/nisar-solid/ATBD/pull/23#discussion_r860012964
**Reminders**
> bugfix for manually specified site_list_file in `gps.search_gps()`

- mintpy/closure_phase_bias.py
- mintpy/defaults/smallbaselineApp.cfg
- mintpy/diff.py
- mintpy/generate_mask.py
- mintpy/image_stitch.py
- mintpy/legacy/select_network.py
- mintpy/modify_network.py
- mintpy/multi_transect.py
- mintpy/prep_gamma.py
- mintpy/prep_roipac.py
- mintpy/prep_snap.py
- mintpy/reference_point.py
- mintpy/subset.py
- mintpy/timeseries2velocity.py
- mintpy/utils/arg_group.py
- mintpy/utils/plot.py
- mintpy/utils/utils0.py
**Fix spelling errors and typos**
Fix spelling errors and typos in different files (mostly online help messages of the CLI).
.
**Reminders**
> Fix spelling errors and typos

- docs/installation.md
- mintpy/diff.py
- mintpy/iono_tec.py
- mintpy/plot_transection.py
- mintpy/utils/plot.py
- mintpy/view.py
+ fix the `plot_transection.py` bug (#777) identified by @yjzhenglamarmota.
+ plus a few minor changes in:
- iono_tec.py
- view.py
- plot.plot_colobar()
- diff.py
**Reminders**
> plot_transection: bugfix for `add_arrow()`

- docs/README.md
- mintpy/smallbaselineApp.py
- Changed the word Goodle to Google
**Reminders**
> Fixed a minor typo on README.md and smallbaselineApp.py

- .circleci/config.yml
- mintpy/load_data.py
- mintpy/timeseries2velocity.py
- mintpy/tsview.py
+ tsview:
- update its model/time func usage to the latest timeseries2velocity/time_func (#795)
- remove the unnecessary np.array() call while updating image array
+ load_data: align the long global variable names, for readability (#780)
**Reminders**
> tsview: update to the latest timeseries2velocity

- mintpy/smallbaselineApp.py
- mintpy/utils/utils.py
- mintpy/utils/utils1.py
+ now the MintPy custom metadata from your template will be added to the ionStack while:
e.g., `smallbaselineApp.py AqabaSenAT087.cfg --dostep load_data`
This action was already be applied to `ifgramStack.h5` and `geometry*.h5`.
**Reminders**
> smallbaselineApp: get ionStack file & add metadata from custom template file

- mintpy/load_data.py
- mintpy/prep_aria.py
- mintpy/prep_fringe.py
- mintpy/utils/utils0.py
`prep_fringe.py`:
fix a bug to correctly get connected component files from unwrapped file names
make the date parsing from the unw filenames more robust
`prep_aria.py`:
fix bug that tries to parse an input option that doesn't (no longer?) exists
> bugfix in `prep_aria/fringe.py`

- mintpy/objects/gps.py
bugfix on the string for identifying the component
Use "vert" and "vertical" for vertical component; "horz" and "horizontal" for horizontal component.
**Reminders**
> gps: more component string choices

- docs/installation.md
Add installation instructions for Debian as discusses in #810.
**Reminders**
> Add installation instructions for Debian

- mintpy/objects/ionex.py
Fix the bug in `mintpy.objects.ionex.dload_ionex()` as reported by @vbrancat.
**Reminders**
> bugfix in ionex.dload_ionex()

- docs/installation.md
- mintpy/utils/readfile.py
+ readfile.read_isce_xml: bugfix when v_first=0, which is a valid value
+ installation: add recommend to the pip install dev mode
**Reminders**
> readfile.read_isce_xml: bugfix when v_first=0

- mintpy/utils/plot.py
- mintpy/utils/utils1.py
Support binary file in `utils.utils1.add_attribute()` by writing roipac RSC file, in addition to the existing HDF5 file.
**Reminders**
> ut.add_attribute(): support binary file type

- mintpy/objects/ionex.py
> ionex: split `interp_3d_maps()` out of `get_ionex_value()` for re-use

- .circleci/config.yml
- mintpy/cli/load_data.py
- mintpy/cli/save_gmt.py
- mintpy/tsview.py
+ `.circleci/config.yml` updates:
- use $BASH_ENV to set and share environment variable (PATH) among multiple run steps
- rename to workflow/job to "unit-n-workflow-tests"
+ `save_gmt`: fix the typo in the module import (#900)
+ `cli/load_data`: check `-t smallbaselineApp.cfg` existence and print out error msg (https://github.com/insarlab/MintPy/issues/891#issuecomment-1304881338)
+ `tsview`: show the reference index/date info on the slider as title
**Reminders**
> update circle CI + bugfix in save_gmt

- src/mintpy/save_kite.py
A typo was spotted in `save_kite.py`. 
**Reminders**
> save_kite: typo fixed on 'capitalize()'

- src/mintpy/cli/save_gbis.py
- src/mintpy/save_gbis.py
- Ability to extract other dataset from the velocity files in save_gbis.py such as step, and polynomial functions
- This PR is adapted from https://github.com/insarlab/MintPy/pull/874
**Reminders**
> save_gbis: support non-velocity dataset from the velocity file

- .github/ISSUE_TEMPLATE/bug_report.md
- docs/README.md
- docs/installation.md
- src/mintpy/cli/smallbaselineApp.py
- src/mintpy/objects/sensor.py
- src/mintpy/smallbaselineApp.py
+ objects.sensor: add ICEYE parameters
+ docs/comments: add space after # to improve readability
**Reminders**
> sensor: add ICEYE parameters

- src/mintpy/cli/save_gbis.py
- src/mintpy/cli/save_roipac.py
> Fixed some typos

- src/mintpy/utils/isce_utils.py
- src/mintpy/view.py
+ utils/isce_utils: add unwrap_icu() for pythonic re-use
+ view: ignore whitespaces in output figure file name
**Reminders**
> isce_utils: add unwrap_icu()

- src/mintpy/__main__.py
+ add `mintpy --loglevel / quiet / verbose / debug` options to control the logging level, as suggested by @avalentino in #1017.
+ always turn ON traceback in case of exceptions, as suggested by @scottstanie in #1017
+ add example CLI usage
#168 
**Reminders**
> main CLI: add logging control args + turn on traceback for exceptions

- src/mintpy/view.py
+ `view.prep_slice()`: support quoted lists of characters as inputs so that its parsing behavior is the same as the one in command line
**Reminders**
> `view.prep_slice()`: support quoted lists of characters as inputs

- src/mintpy/objects/sensor.py
+ objects/sensor: add LuTan-1 info
**Reminders**
> `sensor`: add LuTan-1 info

- src/mintpy/asc_desc2horz_vert.py
- src/mintpy/prep_gamma.py
- src/mintpy/utils/arg_utils.py
- src/mintpy/utils/map.py
- src/mintpy/view.py
+ `view`: add `--scalebar-linewidth` option
+ `prep_gamma`: fix the `inps.sensor.lower()` issue when sensor is not specified, i.e. inps.sensor is None, by shifting the `lower()` operation inside `extract_metadata4interferogram()`
+ `asc_desc2horz_vert.get_design_matrix4east_north_up()`: add type checking for the `obs_direction` arg.
**Reminders**
> `view`: add `--scalebar-linewidth` option

- src/mintpy/cli/generate_mask.py
typo , I just added -o
**Reminders**
> fix typo in `generate_mask.py` example usage

- .circleci/config.yml
- .github/release.yml
- src/mintpy/cli/timeseries2velocity.py
+ ignore contributions by bots in release notes via `.github/release.yml` file (https://github.com/isce-framework/snaphu-py/pull/29)
+ `circleci`: replace `mambaforge` with `miniforge3`
+ `timeseries2velocity.py --uncertainty`: more comments and references
**Reminders**
> [mnt] ignore contrib by bots in release notes + use miniforge3 in circleci

- src/mintpy/cli/smallbaselineApp.py
- src/mintpy/cli/unwrap_error_bridging.py
- src/mintpy/cli/unwrap_error_phase_closure.py
- src/mintpy/legacy/select_network.py
- src/mintpy/objects/sensor.py
- src/mintpy/utils/plot.py
- src/mintpy/version.py
+ objects.sensor: add Radarsat-1, Radarsat Constellation Mission, and ALOS-4
+ objects.sensor: add the following parameters for all sensors:
- orbit_inclination
- repeat_cycle
- antenna_width
+ utils.plot.auto_adjust_cmap_lut_and_disp_limit(): skip multilooking for small dset
+ fix typos in references in the help msg of several scripts
+ version: remove the unused website & description variables
**Reminders**
> sensor: add orbit_inclination & repeat_cycle

- pyproject.toml
- src/mintpy/simulation/iono.py
+ pyproject.toml: add readme to the dynamic metadata list, attempting to fix the "Not finding README.md specified in pyprojet.toml" error on PyPI website.
+ simulation.iono.py: fix typo
**Reminders**
> pyproject.toml: add readme to the dynamic metadata list

- src/mintpy/cli/prep_gamma.py
- src/mintpy/load_data.py
- src/mintpy/prep_gamma.py
+ prep_gamma: add --dem option to specify the corresponding DEM file, in order to:
1. determine the dataset coordinate type
2. extract the corresponding geo-coord specific metadata
**Reminders**
> `prep_gamma`: support geocoded Gamma products

- docs/dir_structure.md
- src/mintpy/utils/readfile.py
+ `utils.readfile._attribute_gmtsar2roipac()`: grab `ORBIT_DIRECTION` for gmtsar
**Reminders**
> `readfile`: grab `ORBIT_DIRECTION` for `gmtsar`

- src/mintpy/version.py
> version: add 1.6.1 tag

- src/mintpy/objects/sensor.py
- src/mintpy/utils/network.py
- src/mintpy/utils/ptime.py
+ `objects/sensor`: add UAVSAR-L info
+ `utils.network.py`:
- refactor `critical_perp_baseline()` to incorporate different near_range value of different sensors
- `simulate_coherence_v2()`: add SNR as an input argument
+ `utils.ptime.get_date_range()`: ensure output dt_list is within the input `[dmin, dmax]`
**Reminders**
> `sensor`: add `UAVSAR-L`
